/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 playground.gltf 
*/
import React, { useEffect, useRef, useState } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'

export default function Playground({ camera, helperAction, animationIndex, helper, ...props }) {
    const group = useRef()
    const { invalidate } = useThree()
    // const { nodes, materials, animations } = useGLTF('/assets/models/playground.gltf')
    const { nodes, materials, animations } = useGLTF('/assets/models/playground.gltf', function (gltf) {
        gltf.scene.traverse(function (obj) { obj.frustumCulled = false })
    })
    console.log(camera, helper, helperAction)

    const { actions, mixer } = useAnimations(animations, group)
    useEffect(() => {
        mixer.stopAllAction()
        actions[helperAction]
            .reset()
            .setEffectiveTimeScale(0.5)
            .play()
    }, [helperAction])

    useFrame((state, delta) => {
        mixer?.update(delta)
        invalidate()
    })
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <ambientLight frustumCulled={false} color="#ffffff" intensity={0.5} castShadow />
                <directionalLight frustumCulled={false} color="#ffffff" intensity={1} position={[0, 32, 64]} />
                <group name="fox_rig" position={[0.183, 0.034, 1.211]} rotation={[0, -0.004, 0]} scale={0.001}>
                    <primitive object={nodes.root_3} />
                    <primitive object={nodes['MCH-torsoparent_2']} />
                    <primitive object={nodes['MCH-front_foot_ikparentL_1']} />
                    <primitive object={nodes['MCH-front_thigh_ik_targetparentL_1']} />
                    <primitive object={nodes['MCH-front_foot_ikparentR_1']} />
                    <primitive object={nodes['MCH-front_thigh_ik_targetparentR_1']} />
                    <primitive object={nodes['MCH-foot_ikparentL_2']} />
                    <primitive object={nodes['MCH-thigh_ik_targetparentL_2']} />
                    <primitive object={nodes['MCH-foot_ikparentR_2']} />
                    <primitive object={nodes['MCH-thigh_ik_targetparentR_2']} />
                    <group name="fox_body">
                        <skinnedMesh name="fox_body_1" geometry={nodes.fox_body_1.geometry} material={materials.FoxBody} skeleton={nodes.fox_body_1.skeleton} />
                        <skinnedMesh name="fox_body_2" geometry={nodes.fox_body_2.geometry} material={materials.animalBlack} skeleton={nodes.fox_body_2.skeleton} />
                    </group>
                    <skinnedMesh name="fox_head_hair" geometry={nodes.fox_head_hair.geometry} material={materials.FoxBody} skeleton={nodes.fox_head_hair.skeleton} />
                    <group name="fox_l_eyeball">
                        <skinnedMesh name="fox_l_eyeball_1" geometry={nodes.fox_l_eyeball_1.geometry} material={materials.Cornea} skeleton={nodes.fox_l_eyeball_1.skeleton} />
                        <skinnedMesh name="fox_l_eyeball_2" geometry={nodes.fox_l_eyeball_2.geometry} material={materials.IrisPupil} skeleton={nodes.fox_l_eyeball_2.skeleton} />
                    </group>
                    <skinnedMesh name="fox_l_eyebrow" geometry={nodes.fox_l_eyebrow.geometry} material={materials.animalBlack} skeleton={nodes.fox_l_eyebrow.skeleton} />
                    <skinnedMesh name="fox_nose" geometry={nodes.fox_nose.geometry} material={materials.animalBlack} skeleton={nodes.fox_nose.skeleton} />
                    <group name="fox_r_eyeball">
                        <skinnedMesh name="fox_r_eyeball_1" geometry={nodes.fox_r_eyeball_1.geometry} material={materials.Cornea} skeleton={nodes.fox_r_eyeball_1.skeleton} />
                        <skinnedMesh name="fox_r_eyeball_2" geometry={nodes.fox_r_eyeball_2.geometry} material={materials.IrisPupil} skeleton={nodes.fox_r_eyeball_2.skeleton} />
                    </group>
                    <skinnedMesh name="fox_r_eyebrow" geometry={nodes.fox_r_eyebrow.geometry} material={materials.animalBlack} skeleton={nodes.fox_r_eyebrow.skeleton} />
                </group>
                <PerspectiveCamera name="Camera01" makeDefault={camera === 1} far={1000} near={0.1} fov={11.016} position={[0.22, 0.077, 1.417]} rotation={[-0.176, 0.278, 0.096]} />
                <PerspectiveCamera name="Camera02" makeDefault={camera === 2} far={1000} near={0.1} fov={11.016} position={[0.088, 0.071, 1.121]} rotation={[-0.206, -0.603, -0.071]} />
                <PerspectiveCamera name="Camera03" makeDefault={camera === 3} far={1000} near={0.1} fov={11.016} position={[0.012, 0.071, 0.621]} rotation={[-0.247, -1.076, -0.144]} />
                <PerspectiveCamera name="Camera04" makeDefault={camera === 4} far={1000} near={0.1} fov={11.016} position={[0.205, 0.221, 0.332]} rotation={[-2.296, -1.344, -2.262]} />
                <PerspectiveCamera name="Camera05" makeDefault={camera === 5} far={1000} near={0.1} fov={11.016} position={[-0.03, 0.077, 0.316]} rotation={[-0.171, -0.155, 0.02]} />
                <PerspectiveCamera name="Camera06" makeDefault={camera === 6} far={1000} near={0.1} fov={11.016} position={[0.232, 0.105, 0.308]} rotation={[-0.18, -0.343, -0.014]} />
                <PerspectiveCamera name="Camera07" makeDefault={camera === 7} far={1000} near={0.1} fov={11.016} position={[0.181, 0.105, 0.308]} rotation={[-0.18, -0.343, -0.014]} />
                <PerspectiveCamera name="Camera08" makeDefault={camera === 8} far={1000} near={0.1} fov={11.016} position={[0.246, 0.089, 0.308]} rotation={[-0.18, -0.343, -0.014]} />
                <PerspectiveCamera name="Camera09" makeDefault={camera === 9} far={1000} near={0.1} fov={11.016} position={[0.01, 0.086, -0.024]} rotation={[-0.206, -0.603, -0.071]} />
                <PerspectiveCamera name="Camera10" makeDefault={camera === 10} far={1000} near={0.1} fov={11.016} position={[0.029, 0.098, -0.099]} rotation={[-0.206, -0.603, -0.071]} />
                <PerspectiveCamera name="Camera11" makeDefault={camera === 11} far={1000} near={0.1} fov={11.016} position={[0.254, 0.116, 0.004]} rotation={[-0.406, 1.13, 0.418]} />
                <PerspectiveCamera name="Camera12" makeDefault={camera === 12} far={1000} near={0.1} fov={11.016} position={[-0.281, 0.211, -0.415]} rotation={[-2.961, 0.352, 3.126]} />
                <PerspectiveCamera name="Camera13" makeDefault={camera === 13} far={1000} near={0.1} fov={11.016} position={[0.236, 0.135, 0.295]} rotation={[-2.452, 1.303, 2.517]} />
                <PerspectiveCamera name="Camera14" makeDefault={camera === 14} far={1000} near={0.1} fov={11.016} position={[0.412, 0.087, 0.385]} rotation={[-Math.PI, 1.556, -Math.PI]} />
                <group name="bkrnd_trees" position={[-1.43, -0.226, -3.597]} rotation={[0, 1.066, 0]}>
                    <mesh name="bkrnd_trees_1" geometry={nodes.bkrnd_trees_1.geometry} material={materials.wood} />
                    <mesh name="bkrnd_trees_2" geometry={nodes.bkrnd_trees_2.geometry} material={materials.green} />
                </group>
                <group name="foreground_trees">
                    <mesh name="foreground_trees_1" geometry={nodes.foreground_trees_1.geometry} material={materials.wood} />
                    <mesh name="foreground_trees_2" geometry={nodes.foreground_trees_2.geometry} material={materials.green} />
                </group>
                <group name="monkeybars" position={[0.522, -0.019, -0.31]} rotation={[-0.055, -0.967, -0.057]} scale={[1.173, 1.237, 1.173]}>
                    <mesh name="monkeybars_1" geometry={nodes.monkeybars_1.geometry} material={materials.wood} />
                    <mesh name="monkeybars_2" geometry={nodes.monkeybars_2.geometry} material={materials.metalRungs} />
                    <mesh name="monkeybars_3" geometry={nodes.monkeybars_3.geometry} material={materials.dirtPile} />
                    <mesh name="monkeybars_4" geometry={nodes.monkeybars_4.geometry} material={materials.redwood} />
                </group>
                <mesh name="shrubs" geometry={nodes.shrubs.geometry} material={materials.green} />
                <group name="sandbox" position={[0.359, 0.001, -0.401]} rotation={[1.423, -1.557, 1.39]} scale={1.332}>
                    <mesh name="sandbox_1" geometry={nodes.sandbox_1.geometry} material={materials.blue_toys} />
                    <mesh name="sandbox_2" geometry={nodes.sandbox_2.geometry} material={materials.sand} />
                    <mesh name="sandbox_3" geometry={nodes.sandbox_3.geometry} material={materials.redwood} />
                </group>
                <group name="slide" position={[-0.054, 0.003, 0.081]} rotation={[-0.021, 0.117, -0.017]}>
                    <mesh name="slide_1" geometry={nodes.slide_1.geometry} material={materials.redwood} />
                    <mesh name="slide_2" geometry={nodes.slide_2.geometry} material={materials.slideSurface} />
                    <mesh name="slide_3" geometry={nodes.slide_3.geometry} material={materials.dirtPile} />
                </group>
                <group name="swings" position={[-0.065, -0.021, -0.478]} rotation={[0.117, -1.291, 0.125]} scale={1.201}>
                    <mesh name="swings_1" geometry={nodes.swings_1.geometry} material={materials.swingSeat} />
                    <mesh name="swings_2" geometry={nodes.swings_2.geometry} material={materials.redwood} />
                    <mesh name="swings_3" geometry={nodes.swings_3.geometry} material={materials.dirtPile} />
                </group>
                <group name="tireswing" position={[0.019, -0.008, -0.088]} scale={1.225}>
                    <mesh name="tireswing_1" geometry={nodes.tireswing_1.geometry} material={materials.tireRope} />
                    <mesh name="tireswing_2" geometry={nodes.tireswing_2.geometry} material={materials.tire} />
                    <mesh name="tireswing_3" geometry={nodes.tireswing_3.geometry} material={materials.redwood} />
                    <mesh name="tireswing_4" geometry={nodes.tireswing_4.geometry} material={materials.dirtPile} />
                </group>
                <group name="trees" position={[-0.61, 0.002, 1.184]} rotation={[0.144, 1.112, -0.268]} scale={[0.36, 0.361, 0.414]}>
                    <mesh name="tree2" geometry={nodes.tree2.geometry} material={materials.wood} />
                    <mesh name="tree2_1" geometry={nodes.tree2_1.geometry} material={materials.green} />
                </group>
                <mesh name="path" geometry={nodes.path.geometry} material={materials.path} position={[0.221, 0.018, 0.366]} rotation={[0, 0.247, 0]} scale={[7.196, 1, 8.913]} />
                <mesh name="ground_1" geometry={nodes.ground_1.geometry} material={materials.green} position={[0, 0.033, 0]} scale={140.059} />
            </group>
        </group>
    )
}

useGLTF.preload('/assets/models/playground.gltf')
